# Configuration settings for the CleanLogin plugin

# Settings section
settings:
  # Delay in seconds before changing the players gamemode from spectator to survival.
  gamemodeDelay: 5

  # Range in blocks to search for a safe location around the player's initial join position.
  # The plugin checks in a cube shaped area, extending this range in all directions (up, down, north, south, east, west) from the player's current location.
  # Example: A range of 5 means the plugin checks an 11x11x11 area centered on the player's location.
  safeLocationRange: 5
